development:
  adapter: postgresql
  encoding: unicode
  database: sampleapp
  port: 5432
  username: root
  password: exa10sept
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['PRODUCTION_DATABASE']%>
  port: 5432
  username: <%= ENV['PRODUCTION_USERNAME']%>
  password: <%= ENV['PRODUCTION_PASSWORD']%>
  host: <%= ENV['PRODUCTION_HOST']%>

test:
  adapter: postgresql
  encoding: unicode
  database: sampleapp
  port: 5432 
  username: root
  password: exa10sept
  host: localhost

